version: 0.0
os: linux
files:
  - source: /images/
    destination: /root/photos/
hooks:
  BeforeInstall:
    - location: scripts/start_docker
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/point_reconstruction
      runas: root
  ApplicationStop:
    - location: scripts/stop_docker
      timeout: 300
      runas: root
